function output = ballbotControllerUpdate( ...
    estimate, command, previousVelocityIntegral, enable, ...
    previousYawBiasReady, biasDiagnostics, p)
%BALLBOTCONTROLLERUPDATE Pack the stateless controller outputs for Simulink.

yawBiasReady = ballbotYawBiasStartupGuard(previousYawBiasReady ~= 0, ...
    estimate(6), biasDiagnostics(2) ~= 0, p);
yawControlEnabled = yawBiasReady || ...
    abs(command(3)) > p.controller.yawBiasCommandBypassThreshold;
[requestedTorque, nextVelocityIntegral, mode] = ballbotControlStep( ...
    estimate, command, previousVelocityIntegral, enable ~= 0, p, ...
    yawControlEnabled);
output = [requestedTorque; nextVelocityIntegral; double(mode); ...
    double(yawBiasReady)];
end
