function wheelRate = ballbotWheelRateFromDisplacement( ...
    wheelDisplacement, previousWheelDisplacement, sampleTime, ...
    encoderQuantum)
%BALLBOTWHEELRATEFROMDISPLACEMENT Compute wheel rate by backward difference.
%   Both displacements are first rounded onto the encoder count grid, so
%   the finite 341.2 PPR resolution of the FIT0521 encoder is modeled at
%   the control sample rate instead of a continuous-time discontinuity.

wheelRate = (round(wheelDisplacement(:)/encoderQuantum) - ...
    round(previousWheelDisplacement(:)/encoderQuantum))* ...
    encoderQuantum/sampleTime;
end
