function output = ballbotSpeedPiMotorStep( ...
    speedCommand, wheelSpeed, previousIntegral, mode, p)
%BALLBOTSPEEDPIMOTORSTEP Speed PI, MDD3A voltage limit, and DC motor.

controllerOutput = ballbotMdd3aVoltageController( ...
    speedCommand, wheelSpeed, previousIntegral, mode, p);
voltage = controllerOutput(1:3);
nextIntegral = controllerOutput(4:6);

current = (voltage - p.motor.backEmfConstant*wheelSpeed)/ ...
    p.motor.armatureResistance;
current = min(max(current, -p.driver.continuousCurrent), ...
    p.driver.continuousCurrent);
motorTorque = p.motor.torqueConstant*current - ...
    p.motor.viscousFriction*wheelSpeed;
torqueLimit = p.driver.continuousTorqueLimit;
if isfield(p.controller, "fullplant") && ...
        isfield(p.controller.fullplant, "enabled") && ...
        p.controller.fullplant.enabled
    torqueLimit = min(p.controller.tractionLimitedWheelTorque, ...
        p.controller.fullplant.motorTorqueLimit);
end
motorTorque = min(max(motorTorque, -torqueLimit), torqueLimit);
output = [motorTorque; nextIntegral];
end
