% Review the saved Full Multibody operating-point and FRF evidence.
evidenceFile = fullfile(fileparts(mfilename("fullpath")), ...
    "fullplant_identification_evidence.mat");
data = load(evidenceFile, "fullplantEvidence");
evidence = data.fullplantEvidence;

fprintf("Operating-point result: %s\n", ...
    string(evidence.trimReport.TerminationString));
fprintf("Maximum trim constraint violation: %.9g\n", ...
    evidence.trimReport.OptimizationOutput.constrviolation);
fprintf("Linear model: %d outputs, %d inputs, %d states\n", ...
    size(evidence.linearPlant, 1), size(evidence.linearPlant, 2), ...
    order(evidence.linearPlant));
fprintf("FRF amplitudes: %s rad/s\n", ...
    mat2str(evidence.frfAmplitude));
fprintf("Relative linear/FRF mismatch: %s\n", ...
    mat2str(evidence.relativeMismatch20To100RadPerSec, 5));
fprintf("FRF amplitude spread: %.6g\n", ...
    evidence.amplitudeSpread20To100RadPerSec);
fprintf("Analytical X/Y cross-coupling: %.6g dB\n", ...
    evidence.xyCouplingDb20To100RadPerSec);
